name: Organized Scene Renamer
description: Renames only organized scenes to "Performer(s) - YYYY - Title [Studio]" format.
version: 1.0
exec:
  - python3
  - organizedscenerenamer.py
args:
  - name: dry_run
    type: boolean
    label: Dry Run
    default: true
    description: If true, only show planned renames without changing files.

mode: ["bulk", "scene"]
